# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cookbook-client}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Opscode, Inc."]
  s.date = %q{2009-11-09}
  s.default_executable = %q{spoon}
  s.email = %q{info@opscode.com}
  s.executables = ["spoon"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "NOTICE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/spoon",
     "cookbook-client.gemspec",
     "lib/chef/cookbook_client.rb",
     "lib/chef/remote_cookbook.rb",
     "lib/chef/streaming_cookbook_uploader.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/spoon/spoon_spec.rb"
  ]
  s.homepage = %q{http://cookbooks.opscode.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A command-line tool for interacting with the Cookbook Community Site, cookbooks.opscode.com}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/spoon/spoon_spec.rb",
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mixlib-authentication>, [">= 0"])
      s.add_runtime_dependency(%q<opscode-rest>, [">= 0"])
    else
      s.add_dependency(%q<mixlib-authentication>, [">= 0"])
      s.add_dependency(%q<opscode-rest>, [">= 0"])
    end
  else
    s.add_dependency(%q<mixlib-authentication>, [">= 0"])
    s.add_dependency(%q<opscode-rest>, [">= 0"])
  end
end
